module.exports = [
  {
    username: "VJQSw",
    password: "UcQTOi",
    email: "aZJm5@email.com",
    messenger: "UOuKT",
    role: ["design"],
    stack: ["mern", "net", "python", "ruby"],
    size: 3,
    roleAssoc: ["design"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "lWAUv",
    password: "fBKnhQ",
    email: "MCA4h@email.com",
    messenger: "SHA83",
    role: ["design", "backend"],
    stack: ["ruby", "lamp", "python"],
    size: 2,
    roleAssoc: ["backend", "design"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "vtR7d",
    password: "LL9707",
    email: "Eg3U8@email.com",
    messenger: "8DKSY",
    role: ["backend", "design", "frontend"],
    stack: ["mern"],
    size: 1,
    roleAssoc: ["design"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "OmsDY",
    password: "NNIG2J",
    email: "RFKPv@email.com",
    messenger: "B88iS",
    role: ["frontend", "design", "backend"],
    stack: ["mern", "python"],
    size: 2,
    roleAssoc: ["frontend", "backend"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "mAo1q",
    password: "QhWvdY",
    email: "RkMMx@email.com",
    messenger: "Ovwqd",
    role: ["frontend"],
    stack: ["mean"],
    size: 1,
    roleAssoc: ["frontend", "backend"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "HCXTO",
    password: "o0EZn8",
    email: "NOov3@email.com",
    messenger: "JfHN2",
    role: ["frontend"],
    stack: ["python", "mern"],
    size: 2,
    roleAssoc: ["backend", "design"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "kFhYO",
    password: "RtkoLh",
    email: "0YLSn@email.com",
    messenger: "4GxS7",
    role: ["design", "frontend"],
    stack: ["ruby", "python"],
    size: 2,
    roleAssoc: ["backend", "frontend", "design"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "OGTSS",
    password: "ofPKcN",
    email: "GpGoj@email.com",
    messenger: "6cdJC",
    role: ["design", "backend"],
    stack: ["ruby", "lamp", "mern"],
    size: 1,
    roleAssoc: ["backend", "design"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "b9myk",
    password: "tT8RdI",
    email: "71kLm@email.com",
    messenger: "1F6pe",
    role: ["backend"],
    stack: ["mern", "net", "mean", "lamp", "ruby", "python"],
    size: 3,
    roleAssoc: ["design", "backend", "frontend"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "tivmG",
    password: "yuXKuI",
    email: "B69R2@email.com",
    messenger: "MVxCc",
    role: ["design", "backend", "frontend"],
    stack: ["net", "lamp"],
    size: 2,
    roleAssoc: ["backend", "frontend"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "PevbU",
    password: "d2wqwj",
    email: "BAQfR@email.com",
    messenger: "f06YV",
    role: ["backend", "frontend"],
    stack: ["ruby", "mean"],
    size: 1,
    roleAssoc: ["backend", "design"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "mRW6q",
    password: "EbIIbF",
    email: "DCPNx@email.com",
    messenger: "G9Ogg",
    role: ["backend", "frontend", "design"],
    stack: ["mern", "lamp", "ruby", "mean", "python"],
    size: 1,
    roleAssoc: ["backend"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "ayPNk",
    password: "tslncG",
    email: "Th1FX@email.com",
    messenger: "s27bP",
    role: ["backend"],
    stack: ["mean", "ruby", "lamp", "mern"],
    size: 2,
    roleAssoc: ["frontend", "design", "backend"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "lYt07",
    password: "WWUiXT",
    email: "SfjwD@email.com",
    messenger: "hngVY",
    role: ["design"],
    stack: ["lamp", "mern", "mean", "net", "ruby", "python"],
    size: 3,
    roleAssoc: ["design", "backend"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "qa1qf",
    password: "dhst7v",
    email: "L59a2@email.com",
    messenger: "KMOR3",
    role: ["backend", "design", "frontend"],
    stack: ["mean", "python", "mern", "lamp", "ruby", "net"],
    size: 3,
    roleAssoc: ["frontend", "backend"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "VCmxu",
    password: "gdIhpk",
    email: "yYOwm@email.com",
    messenger: "RFTqr",
    role: ["backend", "frontend"],
    stack: ["mean", "python", "lamp", "mern"],
    size: 1,
    roleAssoc: ["frontend", "design"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "DGyV7",
    password: "o4tsk6",
    email: "vhSot@email.com",
    messenger: "nF1Rl",
    role: ["frontend"],
    stack: ["net", "lamp", "mean", "mern", "python", "ruby"],
    size: 3,
    roleAssoc: ["backend", "design"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "i04ys",
    password: "S1rjdb",
    email: "mqXlr@email.com",
    messenger: "s6zj3",
    role: ["design", "backend", "frontend"],
    stack: ["mern", "lamp", "mean", "ruby"],
    size: 1,
    roleAssoc: ["design", "frontend", "backend"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "CFWjV",
    password: "RQ7AZr",
    email: "yTopU@email.com",
    messenger: "l8Dzw",
    role: ["backend"],
    stack: ["mean", "lamp", "net"],
    size: 1,
    roleAssoc: ["backend", "frontend", "design"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "9H11l",
    password: "Fe4F3b",
    email: "m9YYT@email.com",
    messenger: "s09pa",
    role: ["frontend", "design"],
    stack: ["lamp", "net"],
    size: 1,
    roleAssoc: ["backend", "frontend"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "PXD2B",
    password: "U7gMEI",
    email: "Bpce8@email.com",
    messenger: "7DSO8",
    role: ["design"],
    stack: ["lamp", "ruby", "mean", "mern", "python", "net"],
    size: 2,
    roleAssoc: ["design", "frontend", "backend"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "ugnrK",
    password: "zKWsf4",
    email: "txmNM@email.com",
    messenger: "lqmPd",
    role: ["frontend", "backend", "design"],
    stack: ["mern"],
    size: 3,
    roleAssoc: ["backend", "frontend"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "0A8ak",
    password: "XVBB6h",
    email: "IYyfQ@email.com",
    messenger: "ngPZW",
    role: ["backend"],
    stack: ["mean", "net", "mern", "lamp", "ruby"],
    size: 1,
    roleAssoc: ["frontend", "design", "backend"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "RC9kN",
    password: "D9oO5P",
    email: "BndYo@email.com",
    messenger: "deoUw",
    role: ["design"],
    stack: ["mean", "mern", "lamp", "ruby", "python"],
    size: 3,
    roleAssoc: ["frontend"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "P7yyw",
    password: "LPlqKp",
    email: "1BnTJ@email.com",
    messenger: "xX00t",
    role: ["frontend", "backend"],
    stack: ["ruby", "mern"],
    size: 2,
    roleAssoc: ["frontend", "backend", "design"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "6kVXy",
    password: "PDlD0W",
    email: "XPiWb@email.com",
    messenger: "qrnPK",
    role: ["design"],
    stack: ["mean", "mern", "python", "net", "ruby"],
    size: 2,
    roleAssoc: ["design", "frontend", "backend"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "M6VNN",
    password: "Te15Yt",
    email: "jT8Ou@email.com",
    messenger: "3ydvC",
    role: ["frontend", "design"],
    stack: ["mean", "python", "mern", "lamp"],
    size: 1,
    roleAssoc: ["design"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "4m4ZK",
    password: "QszLbG",
    email: "DFZyb@email.com",
    messenger: "SFQAQ",
    role: ["backend", "design", "frontend"],
    stack: ["net", "mean", "ruby", "python"],
    size: 3,
    roleAssoc: ["frontend", "backend"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "9MoXL",
    password: "WJ1UVp",
    email: "mdTFE@email.com",
    messenger: "ATs0W",
    role: ["frontend", "design"],
    stack: ["python", "net", "ruby", "mern", "lamp"],
    size: 3,
    roleAssoc: ["backend", "frontend"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "l6eeC",
    password: "jrYUQw",
    email: "OYWmh@email.com",
    messenger: "Tfozn",
    role: ["backend", "frontend"],
    stack: ["lamp", "mean", "python", "ruby", "mern", "net"],
    size: 2,
    roleAssoc: ["frontend", "backend", "design"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "LQufZ",
    password: "K9meCI",
    email: "2KaVP@email.com",
    messenger: "BHw1W",
    role: ["frontend", "backend"],
    stack: ["mean", "ruby"],
    size: 2,
    roleAssoc: ["backend"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "MC78r",
    password: "1JcLdj",
    email: "vyMKr@email.com",
    messenger: "NCiUw",
    role: ["frontend", "design", "backend"],
    stack: ["lamp", "net", "mern", "mean", "ruby", "python"],
    size: 2,
    roleAssoc: ["frontend", "design"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "AJxgV",
    password: "1HZJlt",
    email: "CyW57@email.com",
    messenger: "q1ka1",
    role: ["frontend", "backend", "design"],
    stack: ["net", "lamp"],
    size: 1,
    roleAssoc: ["design", "backend"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "iijXj",
    password: "LQfcIv",
    email: "Sgu0L@email.com",
    messenger: "9rIEh",
    role: ["design", "frontend", "backend"],
    stack: ["python", "net"],
    size: 1,
    roleAssoc: ["design", "backend"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "g8oKn",
    password: "ZvLZcQ",
    email: "3KOTN@email.com",
    messenger: "wjNwS",
    role: ["frontend"],
    stack: ["lamp", "net", "python", "mean"],
    size: 2,
    roleAssoc: ["design", "backend", "frontend"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "4WPrw",
    password: "ATBzT1",
    email: "iLimR@email.com",
    messenger: "MWY35",
    role: ["backend", "frontend", "design"],
    stack: ["ruby", "lamp"],
    size: 2,
    roleAssoc: ["backend"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "toUJB",
    password: "r5ziFQ",
    email: "Fr0I3@email.com",
    messenger: "ZoRBs",
    role: ["design", "backend"],
    stack: ["net"],
    size: 2,
    roleAssoc: ["backend", "frontend"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "VhIbj",
    password: "eM0hXL",
    email: "la2sm@email.com",
    messenger: "MhHB1",
    role: ["frontend", "design"],
    stack: ["mern", "mean", "python", "ruby", "lamp"],
    size: 1,
    roleAssoc: ["design"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "x5jqa",
    password: "9ixAPq",
    email: "QIynV@email.com",
    messenger: "qBzG1",
    role: ["design", "backend", "frontend"],
    stack: ["lamp", "net", "ruby"],
    size: 3,
    roleAssoc: ["backend"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "D4VFx",
    password: "tdMh8s",
    email: "jyYdd@email.com",
    messenger: "LdbHw",
    role: ["design"],
    stack: ["python", "mern"],
    size: 3,
    roleAssoc: ["frontend"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "tVaZH",
    password: "dTOsnp",
    email: "vT3Em@email.com",
    messenger: "9L9Nm",
    role: ["backend", "frontend", "design"],
    stack: ["lamp", "mern", "mean", "ruby", "net", "python"],
    size: 3,
    roleAssoc: ["backend"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "k0vB4",
    password: "7MBTeC",
    email: "lvay7@email.com",
    messenger: "KovLk",
    role: ["design", "frontend"],
    stack: ["net", "ruby", "lamp", "python"],
    size: 3,
    roleAssoc: ["frontend", "design"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "PUvlp",
    password: "s3E3L8",
    email: "2tbIZ@email.com",
    messenger: "In8D2",
    role: ["design"],
    stack: ["ruby", "mean", "mern", "net", "python"],
    size: 2,
    roleAssoc: ["frontend", "design", "backend"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "L9R56",
    password: "xZz8Ac",
    email: "MolnN@email.com",
    messenger: "hmj8l",
    role: ["frontend", "backend"],
    stack: ["net", "mern", "ruby", "python", "mean"],
    size: 1,
    roleAssoc: ["backend", "design", "frontend"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "kX9US",
    password: "oi7jdt",
    email: "1YNFs@email.com",
    messenger: "3PyMP",
    role: ["backend", "design"],
    stack: ["ruby"],
    size: 2,
    roleAssoc: ["backend", "design"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "W0aIp",
    password: "uAdzEK",
    email: "O4DDy@email.com",
    messenger: "QQHG4",
    role: ["frontend", "design"],
    stack: ["mern", "ruby"],
    size: 2,
    roleAssoc: ["frontend", "backend", "design"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "rzJ2X",
    password: "7YpEv3",
    email: "rkY4q@email.com",
    messenger: "RT6uq",
    role: ["frontend", "design", "backend"],
    stack: ["lamp", "mean", "net"],
    size: 3,
    roleAssoc: ["backend", "frontend"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "8cRsM",
    password: "zjPGaz",
    email: "xlIlP@email.com",
    messenger: "jAxSA",
    role: ["design", "backend", "frontend"],
    stack: ["python", "lamp", "mern", "net", "mean", "ruby"],
    size: 1,
    roleAssoc: ["design"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "OItht",
    password: "OxMiwf",
    email: "TeAey@email.com",
    messenger: "toNs3",
    role: ["frontend", "design", "backend"],
    stack: ["ruby", "python", "net", "lamp", "mern"],
    size: 2,
    roleAssoc: ["design", "backend"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "d1Euy",
    password: "aNvpZj",
    email: "b1DX1@email.com",
    messenger: "wEBWh",
    role: ["design", "frontend"],
    stack: ["net", "mern", "ruby", "mean", "python", "lamp"],
    size: 2,
    roleAssoc: ["design"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "GvZTm",
    password: "1FcGTa",
    email: "8Fgh9@email.com",
    messenger: "3aLib",
    role: ["frontend", "design"],
    stack: ["net", "mern", "ruby", "lamp", "mean", "python"],
    size: 2,
    roleAssoc: ["frontend"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "sVWDe",
    password: "W8hIei",
    email: "iFJA9@email.com",
    messenger: "A2InF",
    role: ["backend"],
    stack: ["python", "mean", "mern", "ruby", "lamp"],
    size: 3,
    roleAssoc: ["frontend", "backend", "design"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "7mjBK",
    password: "TZrvZv",
    email: "zyxJP@email.com",
    messenger: "ZaIIT",
    role: ["backend", "design"],
    stack: ["ruby", "mern", "mean"],
    size: 1,
    roleAssoc: ["backend", "design", "frontend"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "WZW8h",
    password: "3DihZG",
    email: "v9NAo@email.com",
    messenger: "SkrlX",
    role: ["design", "backend", "frontend"],
    stack: ["mean"],
    size: 2,
    roleAssoc: ["design"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "51Njh",
    password: "D6sEx7",
    email: "dogxO@email.com",
    messenger: "fv6YC",
    role: ["design", "backend", "frontend"],
    stack: ["lamp", "mean", "ruby", "python"],
    size: 1,
    roleAssoc: ["design", "backend"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "XiSlD",
    password: "iEBxl8",
    email: "kqPNi@email.com",
    messenger: "WUeVx",
    role: ["backend"],
    stack: ["ruby", "lamp", "mern", "python"],
    size: 2,
    roleAssoc: ["backend", "frontend"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "JftM1",
    password: "oR6pBl",
    email: "1Z8qs@email.com",
    messenger: "HDVmS",
    role: ["frontend", "backend", "design"],
    stack: ["mern", "mean", "ruby", "net", "lamp"],
    size: 2,
    roleAssoc: ["backend", "design"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "1uGd2",
    password: "Q66G6B",
    email: "mSkU2@email.com",
    messenger: "6Yi33",
    role: ["frontend", "backend", "design"],
    stack: ["lamp", "mern", "net", "ruby", "mean"],
    size: 1,
    roleAssoc: ["backend", "design"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "5rRCU",
    password: "rvtQyV",
    email: "m4HXJ@email.com",
    messenger: "R3z7G",
    role: ["frontend"],
    stack: ["python", "mean", "lamp", "ruby"],
    size: 2,
    roleAssoc: ["frontend", "design"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "EM5jA",
    password: "8RNje6",
    email: "1hwfd@email.com",
    messenger: "Lrthx",
    role: ["design", "frontend", "backend"],
    stack: ["lamp", "mean", "mern", "ruby"],
    size: 3,
    roleAssoc: ["design"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "wMcNb",
    password: "vjEGVv",
    email: "3QKGb@email.com",
    messenger: "Llyyk",
    role: ["design", "backend"],
    stack: ["mern"],
    size: 1,
    roleAssoc: ["backend", "frontend"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "6cZ1M",
    password: "PTvLi8",
    email: "H0vDH@email.com",
    messenger: "zSLSv",
    role: ["design", "frontend", "backend"],
    stack: ["ruby", "lamp", "mern", "net"],
    size: 3,
    roleAssoc: ["backend", "design", "frontend"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "TOCcB",
    password: "kbYLxW",
    email: "AvJ9k@email.com",
    messenger: "yvSAV",
    role: ["backend"],
    stack: ["ruby", "python"],
    size: 1,
    roleAssoc: ["backend", "design"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "gbwWs",
    password: "WpxfHx",
    email: "qLMxs@email.com",
    messenger: "gRYvD",
    role: ["backend", "design", "frontend"],
    stack: ["mean", "python", "ruby"],
    size: 2,
    roleAssoc: ["frontend", "design", "backend"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "0p0iF",
    password: "pvnMOD",
    email: "hBiwz@email.com",
    messenger: "sUM7R",
    role: ["design"],
    stack: ["mern", "net", "lamp"],
    size: 3,
    roleAssoc: ["frontend", "backend", "design"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "sODkj",
    password: "OBiJF0",
    email: "RKImO@email.com",
    messenger: "WLMsX",
    role: ["frontend", "design"],
    stack: ["lamp"],
    size: 2,
    roleAssoc: ["design", "frontend", "backend"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "RmScd",
    password: "5YFOHz",
    email: "jpQx8@email.com",
    messenger: "J0UO2",
    role: ["frontend", "design", "backend"],
    stack: ["net", "mean", "ruby", "lamp", "python"],
    size: 3,
    roleAssoc: ["design"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "ddLoc",
    password: "uajl6N",
    email: "MHqu6@email.com",
    messenger: "sd3i6",
    role: ["design", "backend", "frontend"],
    stack: ["mean", "mern", "lamp", "python"],
    size: 3,
    roleAssoc: ["frontend", "design"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "U5wQD",
    password: "vUuZWx",
    email: "ei2uQ@email.com",
    messenger: "nuvrO",
    role: ["backend", "frontend", "design"],
    stack: ["python", "ruby", "lamp"],
    size: 3,
    roleAssoc: ["design", "frontend"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "mcoz4",
    password: "q73X8d",
    email: "Zon6y@email.com",
    messenger: "vqlPi",
    role: ["frontend"],
    stack: ["lamp", "mern", "net", "ruby", "mean"],
    size: 1,
    roleAssoc: ["backend"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "zQCEI",
    password: "axPzaB",
    email: "lEoFe@email.com",
    messenger: "K1f2o",
    role: ["frontend", "backend"],
    stack: ["mern", "lamp", "mean", "ruby", "python"],
    size: 1,
    roleAssoc: ["frontend", "design", "backend"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "LQ3Sl",
    password: "kqX1Ix",
    email: "NDBZI@email.com",
    messenger: "QK3Le",
    role: ["design"],
    stack: ["lamp", "mean", "ruby", "python"],
    size: 2,
    roleAssoc: ["design", "frontend", "backend"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "D52Ks",
    password: "FOl24z",
    email: "3hpK2@email.com",
    messenger: "8HGja",
    role: ["frontend", "backend", "design"],
    stack: ["mern", "ruby"],
    size: 2,
    roleAssoc: ["design"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "hVdA1",
    password: "PbGtU7",
    email: "j3a5c@email.com",
    messenger: "nbOmV",
    role: ["frontend"],
    stack: ["mern", "python", "lamp"],
    size: 3,
    roleAssoc: ["backend", "frontend"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "ZAaZo",
    password: "o6EFCJ",
    email: "Aoh0A@email.com",
    messenger: "d0xO2",
    role: ["design"],
    stack: ["net", "mern", "mean", "lamp", "python"],
    size: 3,
    roleAssoc: ["frontend", "backend", "design"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "PFS7Q",
    password: "gSZCta",
    email: "yecxn@email.com",
    messenger: "e71mV",
    role: ["backend", "design", "frontend"],
    stack: ["python", "lamp"],
    size: 1,
    roleAssoc: ["backend"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "RCXut",
    password: "jwdSgU",
    email: "xieT3@email.com",
    messenger: "ulol6",
    role: ["frontend", "design"],
    stack: ["mern"],
    size: 2,
    roleAssoc: ["frontend", "design", "backend"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "ERbfy",
    password: "084cHM",
    email: "QZ10K@email.com",
    messenger: "eepNC",
    role: ["backend", "design", "frontend"],
    stack: ["python", "lamp", "mern"],
    size: 3,
    roleAssoc: ["design"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "Zpqyg",
    password: "bvIdPT",
    email: "r6i5q@email.com",
    messenger: "y5gHy",
    role: ["frontend"],
    stack: ["mean", "mern", "ruby", "lamp", "python"],
    size: 1,
    roleAssoc: ["frontend", "backend", "design"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "QIh82",
    password: "Z7beSA",
    email: "JgWk5@email.com",
    messenger: "Bpt2Z",
    role: ["design", "frontend", "backend"],
    stack: ["mern", "lamp"],
    size: 3,
    roleAssoc: ["backend"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "3VzVe",
    password: "MYT1t5",
    email: "aSxgh@email.com",
    messenger: "aIi1J",
    role: ["design", "backend", "frontend"],
    stack: ["mean", "python", "mern", "ruby", "net"],
    size: 2,
    roleAssoc: ["frontend", "backend"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "PeeVS",
    password: "LvFJem",
    email: "ZEIJu@email.com",
    messenger: "CO8c4",
    role: ["design"],
    stack: ["mean", "net", "lamp", "python"],
    size: 3,
    roleAssoc: ["frontend", "backend", "design"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "QMWv9",
    password: "nQrXYx",
    email: "IvWTF@email.com",
    messenger: "GCqee",
    role: ["backend", "design"],
    stack: ["net", "mern", "lamp"],
    size: 1,
    roleAssoc: ["frontend"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "CscKN",
    password: "hYEcNk",
    email: "NgW1k@email.com",
    messenger: "JFhNI",
    role: ["frontend", "design", "backend"],
    stack: ["net"],
    size: 1,
    roleAssoc: ["frontend"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "HrLJx",
    password: "2BhIPV",
    email: "tihrU@email.com",
    messenger: "6XJcY",
    role: ["backend", "design"],
    stack: ["mern", "net", "python", "mean", "ruby"],
    size: 1,
    roleAssoc: ["backend", "frontend", "design"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "4qPLM",
    password: "jYlTAN",
    email: "TfNku@email.com",
    messenger: "UVsiZ",
    role: ["backend", "frontend"],
    stack: ["ruby", "mean", "python", "mern"],
    size: 3,
    roleAssoc: ["backend", "frontend"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "a6ZHp",
    password: "FNsbam",
    email: "sXAyO@email.com",
    messenger: "HmzOp",
    role: ["frontend", "design", "backend"],
    stack: ["python", "ruby", "lamp", "net"],
    size: 2,
    roleAssoc: ["design", "backend"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "cOfGZ",
    password: "KJk6uO",
    email: "XXgmc@email.com",
    messenger: "29AZU",
    role: ["frontend"],
    stack: ["python", "mean", "ruby", "lamp"],
    size: 1,
    roleAssoc: ["backend", "frontend", "design"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "ZDwZq",
    password: "VDQW9H",
    email: "1EC5v@email.com",
    messenger: "K0wBZ",
    role: ["backend"],
    stack: ["ruby", "python"],
    size: 3,
    roleAssoc: ["frontend", "backend", "design"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "rZwzS",
    password: "WQuRAH",
    email: "h27do@email.com",
    messenger: "v60d3",
    role: ["backend", "design"],
    stack: ["mean"],
    size: 2,
    roleAssoc: ["frontend", "design"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "BPWpr",
    password: "Uab3wj",
    email: "c89pa@email.com",
    messenger: "t3c17",
    role: ["backend", "frontend", "design"],
    stack: ["net", "lamp"],
    size: 2,
    roleAssoc: ["design", "backend", "frontend"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "NsLXV",
    password: "muVrtl",
    email: "RFEC6@email.com",
    messenger: "upqoS",
    role: ["frontend"],
    stack: ["ruby"],
    size: 1,
    roleAssoc: ["backend", "design"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "K54A8",
    password: "bVBLEf",
    email: "g3akk@email.com",
    messenger: "g5tzh",
    role: ["frontend"],
    stack: ["lamp", "python", "ruby"],
    size: 2,
    roleAssoc: ["frontend"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "UPos9",
    password: "tdKHeA",
    email: "MV7eZ@email.com",
    messenger: "8316i",
    role: ["design", "backend"],
    stack: ["mern", "mean"],
    size: 3,
    roleAssoc: ["frontend", "design", "backend"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "aCma0",
    password: "nd3EVo",
    email: "7rHcK@email.com",
    messenger: "R8rFV",
    role: ["frontend", "backend", "design"],
    stack: ["lamp", "mern", "python"],
    size: 3,
    roleAssoc: ["design"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "zForB",
    password: "B6amgP",
    email: "0c8jg@email.com",
    messenger: "FaSQN",
    role: ["frontend", "backend"],
    stack: ["python", "net", "lamp", "mean"],
    size: 3,
    roleAssoc: ["frontend"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "W9Xr2",
    password: "2w7suO",
    email: "YD2Z3@email.com",
    messenger: "umKN7",
    role: ["design", "frontend", "backend"],
    stack: ["ruby", "python", "mern", "net", "mean", "lamp"],
    size: 3,
    roleAssoc: ["design"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "lYkKK",
    password: "e221av",
    email: "R5b9n@email.com",
    messenger: "v89Tc",
    role: ["design", "frontend"],
    stack: ["ruby", "lamp"],
    size: 3,
    roleAssoc: ["backend", "design"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "jXzYC",
    password: "OCVLTl",
    email: "uXctC@email.com",
    messenger: "S0w7K",
    role: ["backend"],
    stack: ["mern", "lamp", "python", "mean", "net", "ruby"],
    size: 3,
    roleAssoc: ["design", "backend"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  },
  {
    username: "LYUC6",
    password: "5TNiVS",
    email: "YpGB3@email.com",
    messenger: "u2AHE",
    role: ["frontend", "design"],
    stack: ["ruby", "lamp", "python", "net"],
    size: 1,
    roleAssoc: ["frontend"],
    team: undefined,
    eventID: "gd9DgPcOUZRuCdazYMNcBYTmHoM2"
  }
];
