module.exports = [
  {
    username: "Xj4zl",
    password: "W3Z3GV",
    email: "zrb8F@email.com",
    messenger: "Slyhh",
    role: ["design"],
    stack: ["lamp", "ruby", "mern", "mean"],
    size: 1,
    roleAssoc: ["backend"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "IZf2k",
    password: "qIoHEU",
    email: "iF7Y7@email.com",
    messenger: "86NJb",
    role: ["design", "backend"],
    stack: ["mern", "net", "mean", "python", "lamp"],
    size: 2,
    roleAssoc: ["backend", "design", "frontend"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "DX3sb",
    password: "94GO2r",
    email: "5fb2C@email.com",
    messenger: "w4oFu",
    role: ["backend"],
    stack: ["lamp", "mern", "python", "net"],
    size: 1,
    roleAssoc: ["frontend", "design", "backend"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "OWt8Y",
    password: "7jP7Ar",
    email: "bE4TH@email.com",
    messenger: "uCxd9",
    role: ["design", "frontend"],
    stack: ["net"],
    size: 2,
    roleAssoc: ["backend", "frontend", "design"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "PiJ94",
    password: "3unhzG",
    email: "s9tuk@email.com",
    messenger: "jzpGw",
    role: ["backend"],
    stack: ["python", "mean", "ruby", "mern", "lamp"],
    size: 2,
    roleAssoc: ["design"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "25bjS",
    password: "T4UxXP",
    email: "Obv2r@email.com",
    messenger: "ZLdPh",
    role: ["backend", "design"],
    stack: ["net", "python", "mean"],
    size: 2,
    roleAssoc: ["backend"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "urKYA",
    password: "Zf7DTh",
    email: "VebZH@email.com",
    messenger: "mHqkQ",
    role: ["design"],
    stack: ["mern", "net", "mean", "ruby"],
    size: 3,
    roleAssoc: ["design"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "VBKwU",
    password: "R5HtQ8",
    email: "ASwWp@email.com",
    messenger: "IhMsJ",
    role: ["frontend", "backend"],
    stack: ["mean", "net", "ruby"],
    size: 2,
    roleAssoc: ["frontend", "backend"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "iik6B",
    password: "MsJMTV",
    email: "KfFw6@email.com",
    messenger: "ZHwF0",
    role: ["design"],
    stack: ["mean", "net"],
    size: 3,
    roleAssoc: ["backend"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "jTHBA",
    password: "9w1L3q",
    email: "25vOy@email.com",
    messenger: "7LGxh",
    role: ["frontend", "backend", "design"],
    stack: ["lamp", "net"],
    size: 3,
    roleAssoc: ["backend", "design"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "Vdn3Y",
    password: "keglzp",
    email: "ftOHu@email.com",
    messenger: "xTsje",
    role: ["backend", "frontend"],
    stack: ["mean", "python", "lamp", "net", "ruby"],
    size: 3,
    roleAssoc: ["design", "frontend", "backend"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "mqwpo",
    password: "LbNuEa",
    email: "mF0qi@email.com",
    messenger: "oJ32W",
    role: ["design", "backend", "frontend"],
    stack: ["net", "ruby", "python"],
    size: 3,
    roleAssoc: ["backend", "frontend", "design"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "yiW0F",
    password: "JOxo3I",
    email: "9RdE2@email.com",
    messenger: "RCYPY",
    role: ["frontend"],
    stack: ["ruby", "lamp", "mern", "net"],
    size: 3,
    roleAssoc: ["design", "backend", "frontend"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "Rk3ML",
    password: "dnnpSx",
    email: "fCgVJ@email.com",
    messenger: "ODlxM",
    role: ["design", "backend", "frontend"],
    stack: ["net", "ruby", "python", "mern", "mean", "lamp"],
    size: 1,
    roleAssoc: ["design", "frontend"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "xMwOa",
    password: "MmsP2i",
    email: "At77r@email.com",
    messenger: "EzrKQ",
    role: ["backend", "design", "frontend"],
    stack: ["mern", "lamp", "mean", "python", "net", "ruby"],
    size: 2,
    roleAssoc: ["backend", "design"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "tJRoU",
    password: "TtyJx7",
    email: "3H75x@email.com",
    messenger: "prOua",
    role: ["backend"],
    stack: ["mern", "python", "ruby", "mean"],
    size: 1,
    roleAssoc: ["backend"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "euJKQ",
    password: "iTwRgl",
    email: "WfPQL@email.com",
    messenger: "0osgW",
    role: ["backend", "design", "frontend"],
    stack: ["mean", "ruby", "mern"],
    size: 3,
    roleAssoc: ["frontend", "design"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "JJgSo",
    password: "PlIJJQ",
    email: "BDSoz@email.com",
    messenger: "AxLM5",
    role: ["frontend"],
    stack: ["net"],
    size: 1,
    roleAssoc: ["design", "backend"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "i2ogC",
    password: "FrnLLD",
    email: "XEgqk@email.com",
    messenger: "n5a3V",
    role: ["frontend"],
    stack: ["mern", "net"],
    size: 3,
    roleAssoc: ["frontend", "design"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "JQHBg",
    password: "TYikss",
    email: "1niGc@email.com",
    messenger: "vCVEX",
    role: ["backend", "design", "frontend"],
    stack: ["mern", "ruby"],
    size: 2,
    roleAssoc: ["backend"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "ozxkR",
    password: "lIEzhq",
    email: "Fzmz5@email.com",
    messenger: "q2RVh",
    role: ["frontend"],
    stack: ["mean", "lamp", "mern", "ruby"],
    size: 3,
    roleAssoc: ["design"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "djPXF",
    password: "ja7tE2",
    email: "NtBX4@email.com",
    messenger: "mXBtE",
    role: ["design", "backend"],
    stack: ["mean", "lamp", "ruby", "mern"],
    size: 1,
    roleAssoc: ["frontend"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "UrMr1",
    password: "35TljH",
    email: "z5ne5@email.com",
    messenger: "CTuOO",
    role: ["backend", "design"],
    stack: ["lamp", "mean"],
    size: 2,
    roleAssoc: ["backend", "design"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "rBRUF",
    password: "nYb2XH",
    email: "kAAie@email.com",
    messenger: "VgrPG",
    role: ["design", "backend"],
    stack: ["lamp", "python"],
    size: 3,
    roleAssoc: ["backend", "frontend"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "xBs5o",
    password: "zkblf5",
    email: "QbAsw@email.com",
    messenger: "5E0kM",
    role: ["design", "backend"],
    stack: ["ruby", "lamp"],
    size: 2,
    roleAssoc: ["frontend", "design", "backend"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "PiZhh",
    password: "U5JIcK",
    email: "x9Czd@email.com",
    messenger: "nBY6M",
    role: ["frontend", "design"],
    stack: ["mean"],
    size: 3,
    roleAssoc: ["design", "backend", "frontend"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "h7LXc",
    password: "3wKh6M",
    email: "Ufjet@email.com",
    messenger: "nYuVy",
    role: ["frontend", "backend", "design"],
    stack: ["lamp", "ruby"],
    size: 1,
    roleAssoc: ["design", "frontend", "backend"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "bxEnL",
    password: "2XL7xZ",
    email: "eALjK@email.com",
    messenger: "Lo99r",
    role: ["backend", "design", "frontend"],
    stack: ["mean", "python", "mern", "net"],
    size: 3,
    roleAssoc: ["design", "backend"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "wuBlj",
    password: "g8GsAo",
    email: "RNhhg@email.com",
    messenger: "qEx0t",
    role: ["design"],
    stack: ["mean", "ruby", "lamp", "python"],
    size: 2,
    roleAssoc: ["design"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "Ig8HH",
    password: "iHdyJ4",
    email: "os8Do@email.com",
    messenger: "R8CJz",
    role: ["backend", "frontend", "design"],
    stack: ["net", "lamp", "ruby", "python", "mean"],
    size: 2,
    roleAssoc: ["design", "backend", "frontend"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "h909a",
    password: "4FTk51",
    email: "SEeG0@email.com",
    messenger: "yYC8N",
    role: ["design"],
    stack: ["lamp", "mean", "ruby", "python", "mern", "net"],
    size: 1,
    roleAssoc: ["design", "frontend", "backend"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "Z5tiD",
    password: "LCBnNV",
    email: "FST9z@email.com",
    messenger: "t41Di",
    role: ["design", "frontend"],
    stack: ["python", "mern", "mean"],
    size: 3,
    roleAssoc: ["design", "backend", "frontend"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "32KkO",
    password: "r7fHsl",
    email: "uZk6W@email.com",
    messenger: "Mt4OI",
    role: ["frontend", "backend"],
    stack: ["mean"],
    size: 1,
    roleAssoc: ["backend", "frontend", "design"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "3Ty1I",
    password: "hfxRys",
    email: "fSKdZ@email.com",
    messenger: "fy99D",
    role: ["frontend", "design"],
    stack: ["lamp"],
    size: 3,
    roleAssoc: ["frontend"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "b3Iaz",
    password: "8iFLO4",
    email: "pUzTD@email.com",
    messenger: "blfeB",
    role: ["backend"],
    stack: ["python"],
    size: 1,
    roleAssoc: ["backend", "frontend"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "TBsEf",
    password: "a1pQl9",
    email: "FVRB9@email.com",
    messenger: "2Vgml",
    role: ["design", "frontend", "backend"],
    stack: ["mern"],
    size: 3,
    roleAssoc: ["frontend", "backend"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "Eiydg",
    password: "3y9HI2",
    email: "3OSIo@email.com",
    messenger: "OsIDE",
    role: ["frontend"],
    stack: ["net", "ruby"],
    size: 3,
    roleAssoc: ["backend", "frontend"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "a47jq",
    password: "8XcGpQ",
    email: "sYFCI@email.com",
    messenger: "GmUPJ",
    role: ["design", "backend", "frontend"],
    stack: ["lamp"],
    size: 2,
    roleAssoc: ["frontend", "design"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "noiMC",
    password: "F2xlDc",
    email: "nbHMT@email.com",
    messenger: "VD3e1",
    role: ["frontend"],
    stack: ["ruby"],
    size: 2,
    roleAssoc: ["backend"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "QWrZz",
    password: "wfkLu2",
    email: "hgzAv@email.com",
    messenger: "KNQXE",
    role: ["design", "frontend"],
    stack: ["lamp", "ruby"],
    size: 2,
    roleAssoc: ["design", "backend"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "du6xX",
    password: "qw8Ppi",
    email: "voVVb@email.com",
    messenger: "BrzoS",
    role: ["backend", "frontend"],
    stack: ["mern"],
    size: 2,
    roleAssoc: ["frontend"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "D4oVx",
    password: "vBEQT9",
    email: "8L6VE@email.com",
    messenger: "kO30r",
    role: ["design", "backend"],
    stack: ["ruby", "mean", "lamp"],
    size: 2,
    roleAssoc: ["backend", "frontend", "design"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "Rwgb1",
    password: "ChMtsS",
    email: "r76Rk@email.com",
    messenger: "5nVz9",
    role: ["backend"],
    stack: ["mean", "net", "python", "mern", "lamp", "ruby"],
    size: 1,
    roleAssoc: ["design"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "WKoG3",
    password: "F6pHUS",
    email: "e43Kn@email.com",
    messenger: "7nNHj",
    role: ["frontend"],
    stack: ["python", "mern", "net", "ruby", "mean"],
    size: 3,
    roleAssoc: ["backend", "frontend"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "789Te",
    password: "F7cHoR",
    email: "4woEe@email.com",
    messenger: "stt98",
    role: ["backend", "design"],
    stack: ["ruby", "mern", "lamp", "net", "mean"],
    size: 2,
    roleAssoc: ["frontend"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "xl3PU",
    password: "FV3DiY",
    email: "HuegF@email.com",
    messenger: "bypoT",
    role: ["design"],
    stack: ["lamp", "python", "mern", "ruby", "net"],
    size: 2,
    roleAssoc: ["backend"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "Efnc3",
    password: "EqDYXC",
    email: "PNprk@email.com",
    messenger: "7KZ3h",
    role: ["design", "frontend", "backend"],
    stack: ["mern", "lamp", "ruby", "mean", "python"],
    size: 2,
    roleAssoc: ["backend"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "QAFFp",
    password: "pLQS4X",
    email: "gWQUY@email.com",
    messenger: "8Op1a",
    role: ["frontend", "design", "backend"],
    stack: ["mean"],
    size: 2,
    roleAssoc: ["frontend", "design"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "UE3Xh",
    password: "kidE4x",
    email: "q1Y75@email.com",
    messenger: "5RPAe",
    role: ["frontend"],
    stack: ["ruby", "mean", "python", "net", "mern", "lamp"],
    size: 1,
    roleAssoc: ["backend", "design"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "0gMZQ",
    password: "6G20SA",
    email: "0HYgn@email.com",
    messenger: "zO6IZ",
    role: ["backend"],
    stack: ["lamp", "mern", "mean", "python", "net", "ruby"],
    size: 2,
    roleAssoc: ["design"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "3Rhd7",
    password: "FBMd2b",
    email: "Fdahk@email.com",
    messenger: "ZPSwP",
    role: ["backend"],
    stack: ["mern", "ruby", "mean"],
    size: 1,
    roleAssoc: ["frontend", "backend", "design"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "73AT8",
    password: "djeGBv",
    email: "kJqhc@email.com",
    messenger: "og8Id",
    role: ["design"],
    stack: ["python", "lamp", "ruby", "net", "mean", "mern"],
    size: 2,
    roleAssoc: ["design", "frontend"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "muVjb",
    password: "1Fnbva",
    email: "4L4br@email.com",
    messenger: "75STX",
    role: ["frontend", "backend"],
    stack: ["lamp", "mean", "python", "net", "mern"],
    size: 1,
    roleAssoc: ["backend", "frontend", "design"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "ytPmd",
    password: "zzFyKK",
    email: "gjkdi@email.com",
    messenger: "Stegr",
    role: ["design", "backend", "frontend"],
    stack: ["ruby"],
    size: 1,
    roleAssoc: ["design", "backend", "frontend"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "1XYBM",
    password: "OhdnnJ",
    email: "Nfhp1@email.com",
    messenger: "go0tA",
    role: ["design", "backend"],
    stack: ["net", "python"],
    size: 2,
    roleAssoc: ["design"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "AKc4R",
    password: "nPDwD6",
    email: "djJLB@email.com",
    messenger: "VwIvL",
    role: ["backend"],
    stack: ["net", "python", "mean", "ruby", "lamp", "mern"],
    size: 2,
    roleAssoc: ["design"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "LmHqw",
    password: "bzBtHZ",
    email: "SoJB1@email.com",
    messenger: "FlxXM",
    role: ["design"],
    stack: ["mern", "ruby", "lamp", "net"],
    size: 1,
    roleAssoc: ["backend"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "DTXhB",
    password: "1fJyJ1",
    email: "Z0vxD@email.com",
    messenger: "Dd6si",
    role: ["backend"],
    stack: ["python", "ruby"],
    size: 2,
    roleAssoc: ["design", "frontend", "backend"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "5X9uB",
    password: "6enRbi",
    email: "gybjr@email.com",
    messenger: "xitsN",
    role: ["design"],
    stack: ["lamp", "ruby", "mern"],
    size: 2,
    roleAssoc: ["design", "backend", "frontend"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "zV5OO",
    password: "fPSPIh",
    email: "KKXAr@email.com",
    messenger: "XLeay",
    role: ["frontend"],
    stack: ["python", "lamp", "mean", "net"],
    size: 2,
    roleAssoc: ["backend", "design"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "YEC9A",
    password: "x5XOqg",
    email: "SlWa9@email.com",
    messenger: "t7LWt",
    role: ["design", "frontend"],
    stack: ["python", "lamp", "net", "mean", "ruby"],
    size: 1,
    roleAssoc: ["frontend"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "Lqb33",
    password: "OcCrgx",
    email: "ygraR@email.com",
    messenger: "JDD6D",
    role: ["design", "frontend", "backend"],
    stack: ["net", "python", "mean"],
    size: 1,
    roleAssoc: ["design", "backend"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "SFVBV",
    password: "fP5jBN",
    email: "39O9c@email.com",
    messenger: "LFpRX",
    role: ["backend", "design"],
    stack: ["ruby", "net", "lamp", "mean"],
    size: 1,
    roleAssoc: ["frontend", "design", "backend"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "4PcQB",
    password: "XIsGnO",
    email: "SviJD@email.com",
    messenger: "dKqQO",
    role: ["backend"],
    stack: ["mern", "python", "lamp"],
    size: 2,
    roleAssoc: ["frontend", "design", "backend"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "kYUYB",
    password: "YUFeUk",
    email: "LgIhf@email.com",
    messenger: "A6Kk0",
    role: ["design", "frontend", "backend"],
    stack: ["python"],
    size: 3,
    roleAssoc: ["backend", "frontend"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "AxAzj",
    password: "La9I6v",
    email: "GOoAu@email.com",
    messenger: "inAG1",
    role: ["design", "frontend"],
    stack: ["net"],
    size: 2,
    roleAssoc: ["design", "backend", "frontend"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "7Pn6F",
    password: "NZ6iuD",
    email: "v1rIo@email.com",
    messenger: "fxxat",
    role: ["backend", "design"],
    stack: ["mern", "mean", "python"],
    size: 2,
    roleAssoc: ["design", "frontend"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "N0jwu",
    password: "J6kDdM",
    email: "sGrll@email.com",
    messenger: "BNVRh",
    role: ["frontend"],
    stack: ["net", "lamp", "python", "mern", "mean", "ruby"],
    size: 1,
    roleAssoc: ["frontend"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "RrKDV",
    password: "AywMUQ",
    email: "U56RP@email.com",
    messenger: "O5lab",
    role: ["design"],
    stack: ["net", "mern"],
    size: 1,
    roleAssoc: ["design", "backend", "frontend"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "VkbVD",
    password: "vdynJ8",
    email: "i4wCv@email.com",
    messenger: "BlR9n",
    role: ["frontend"],
    stack: ["python", "mern"],
    size: 3,
    roleAssoc: ["design", "frontend", "backend"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "VVbPH",
    password: "aVKLFj",
    email: "dG31a@email.com",
    messenger: "jSHEx",
    role: ["backend"],
    stack: ["ruby", "lamp", "net", "python", "mern"],
    size: 3,
    roleAssoc: ["frontend"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "RVOxY",
    password: "ycH2vb",
    email: "t5ItL@email.com",
    messenger: "PKDbt",
    role: ["backend"],
    stack: ["mern", "net", "ruby", "python"],
    size: 3,
    roleAssoc: ["design"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "Q0ZJu",
    password: "MzFqjj",
    email: "muLuq@email.com",
    messenger: "eZvV1",
    role: ["frontend"],
    stack: ["net", "ruby", "lamp", "mern"],
    size: 3,
    roleAssoc: ["frontend", "design"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "U2ZHZ",
    password: "fAFqcJ",
    email: "yjN8z@email.com",
    messenger: "exWgd",
    role: ["frontend", "backend"],
    stack: ["net"],
    size: 1,
    roleAssoc: ["backend"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "Qm666",
    password: "elVnRf",
    email: "hv7DW@email.com",
    messenger: "ql76a",
    role: ["frontend", "backend", "design"],
    stack: ["python", "lamp", "net"],
    size: 3,
    roleAssoc: ["frontend"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "afnfs",
    password: "uBmjpK",
    email: "DbbOx@email.com",
    messenger: "0f6bU",
    role: ["frontend", "backend", "design"],
    stack: ["mean", "mern", "ruby", "lamp"],
    size: 3,
    roleAssoc: ["backend", "design", "frontend"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "EOGPb",
    password: "gk93Px",
    email: "8EBkl@email.com",
    messenger: "fJm7U",
    role: ["backend", "frontend"],
    stack: ["net", "lamp", "mean"],
    size: 3,
    roleAssoc: ["frontend", "design", "backend"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "CP0ZC",
    password: "bg2vel",
    email: "7v2S2@email.com",
    messenger: "GXK7r",
    role: ["frontend", "backend", "design"],
    stack: ["lamp", "net", "python", "mean"],
    size: 2,
    roleAssoc: ["backend"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "oKfiD",
    password: "mkQfRP",
    email: "FR5Ff@email.com",
    messenger: "QAsxA",
    role: ["frontend", "backend"],
    stack: ["python", "mean", "lamp"],
    size: 2,
    roleAssoc: ["design", "backend", "frontend"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "eBhZa",
    password: "FlvWk9",
    email: "1M1Ub@email.com",
    messenger: "5xPLk",
    role: ["frontend"],
    stack: ["ruby", "mean"],
    size: 3,
    roleAssoc: ["design", "frontend"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "aw2Wq",
    password: "rer5gX",
    email: "hULWv@email.com",
    messenger: "fpIvJ",
    role: ["backend", "frontend"],
    stack: ["ruby", "mean", "mern", "lamp", "net"],
    size: 3,
    roleAssoc: ["backend"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "XJ9r2",
    password: "m8FK2b",
    email: "M0Qcr@email.com",
    messenger: "h8uOd",
    role: ["design", "frontend", "backend"],
    stack: ["python", "ruby"],
    size: 1,
    roleAssoc: ["design", "frontend", "backend"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "xmcIO",
    password: "wEVRqf",
    email: "4ornD@email.com",
    messenger: "AAQS6",
    role: ["design", "backend"],
    stack: ["ruby", "mern"],
    size: 2,
    roleAssoc: ["design"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "zL73N",
    password: "ZGk27Q",
    email: "IfaF2@email.com",
    messenger: "cirrl",
    role: ["frontend"],
    stack: ["ruby"],
    size: 1,
    roleAssoc: ["backend", "design", "frontend"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "oXmCg",
    password: "MJ2LXk",
    email: "w3yB6@email.com",
    messenger: "NxWKF",
    role: ["design", "backend", "frontend"],
    stack: ["mern", "net", "python", "lamp"],
    size: 1,
    roleAssoc: ["design", "backend"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "e54i4",
    password: "gHbv3u",
    email: "OyP23@email.com",
    messenger: "zkVQ6",
    role: ["backend", "design"],
    stack: ["net", "mern", "ruby", "mean"],
    size: 1,
    roleAssoc: ["backend", "frontend"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "uvigY",
    password: "bQPy8p",
    email: "iTmIa@email.com",
    messenger: "9euBs",
    role: ["frontend", "backend"],
    stack: ["ruby", "mean", "python", "mern"],
    size: 3,
    roleAssoc: ["design"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "nMiR7",
    password: "c62RxL",
    email: "NBNDp@email.com",
    messenger: "DPJVg",
    role: ["backend"],
    stack: ["mern", "python", "lamp", "mean"],
    size: 1,
    roleAssoc: ["backend", "frontend", "design"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "MrFWL",
    password: "7LUoB0",
    email: "gwCGU@email.com",
    messenger: "JrqFH",
    role: ["design", "backend", "frontend"],
    stack: ["lamp", "python"],
    size: 2,
    roleAssoc: ["backend"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "qaifZ",
    password: "af1NTQ",
    email: "pWHGW@email.com",
    messenger: "0Lsgr",
    role: ["frontend"],
    stack: ["mean", "net", "lamp", "ruby", "mern"],
    size: 2,
    roleAssoc: ["backend"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "NIPgw",
    password: "Lw8lwA",
    email: "QpYkZ@email.com",
    messenger: "DbRfR",
    role: ["frontend", "design", "backend"],
    stack: ["net", "mern", "ruby", "mean", "lamp"],
    size: 1,
    roleAssoc: ["backend"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "SK2fT",
    password: "4IO2Dr",
    email: "tGVxm@email.com",
    messenger: "3Uk6f",
    role: ["backend"],
    stack: ["mean", "mern", "python"],
    size: 2,
    roleAssoc: ["frontend"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "b1gTL",
    password: "jbMHRO",
    email: "gpVXq@email.com",
    messenger: "fILGx",
    role: ["backend", "frontend"],
    stack: ["python", "ruby", "mern", "lamp"],
    size: 1,
    roleAssoc: ["frontend", "design"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "K8U5U",
    password: "NAqbyM",
    email: "EU1YO@email.com",
    messenger: "mh1CP",
    role: ["frontend", "design", "backend"],
    stack: ["lamp", "ruby", "mern", "mean", "python", "net"],
    size: 3,
    roleAssoc: ["design", "frontend"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "4JPC7",
    password: "CnVvrz",
    email: "IbNHh@email.com",
    messenger: "oF00n",
    role: ["frontend", "design", "backend"],
    stack: ["net", "lamp", "mern", "mean", "ruby"],
    size: 1,
    roleAssoc: ["design"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "kTkfq",
    password: "WVLB9f",
    email: "EeQhW@email.com",
    messenger: "mHKah",
    role: ["design", "frontend"],
    stack: ["mern", "net", "python", "mean", "ruby"],
    size: 2,
    roleAssoc: ["backend"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "6SOZo",
    password: "UsPK5V",
    email: "Gng84@email.com",
    messenger: "32ANl",
    role: ["backend", "frontend", "design"],
    stack: ["mern", "mean", "ruby"],
    size: 2,
    roleAssoc: ["frontend"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "58AVU",
    password: "8l5VxS",
    email: "0bKEN@email.com",
    messenger: "fml6C",
    role: ["design", "frontend", "backend"],
    stack: ["net", "mean"],
    size: 3,
    roleAssoc: ["frontend", "design", "backend"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "3t6JF",
    password: "3DBnJ7",
    email: "dsf7T@email.com",
    messenger: "PutC5",
    role: ["design", "backend"],
    stack: ["mern", "python", "net", "mean"],
    size: 3,
    roleAssoc: ["frontend", "backend"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  },
  {
    username: "fzP6p",
    password: "zTaDhU",
    email: "BZWKP@email.com",
    messenger: "94Yup",
    role: ["frontend", "backend", "design"],
    stack: ["mern"],
    size: 3,
    roleAssoc: ["backend", "design"],
    team: undefined,
    eventID: "aHODgt5c6lZdRshMVT8VubK0huB2"
  }
];
